name: Publish Swagger to SwaggerHub

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  publish-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust based on your project's Node.js version

      - name: Install dependencies
        run: npm install  # Adjust this if you're using a different package manager

      - name: Generate Swagger file
        run: npm run swagger  # Adjust this to your Swagger file generation command

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: docs/swagger.json
          commit-msg: Update Swagger docs file
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Swagger to SwaggerHub
        run: |
          SWAGGER_FILE=docs/swagger.json
          curl -X POST "https://api.swaggerhub.com/apis/NicksDemoOrg/product-apis" \
          -H "Authorization: febe3f85-8bab-4c99-856d-31fbc9e80a97" \
          -H "Content-Type: application/json" \
          --data-binary @$SWAGGER_FILE

      - name: Check for standardization errors
        run: |
          curl -X 'GET' 'https://api.swaggerhub.com/apis/NicksDemoOrg/PayrollAPI/1.0.0/standardization' \
          -H 'accept: application/json' \
          -H 'Authorization: febe3f85-8bab-4c99-856d-31fbc9e80a97'

      # - name: Run test suite through test engine
      #   run: |
      #     testengine -c .\testengine.conf run project tags=pet,user output=C:\Work\Reports environment=dev C:\Work\ready-api-project.xml
      
